Staging creation + github actions setup
Giveth/givpower-subgraph pull request #21
Opened 2022-08-23 22:39 UTC by mateodaza

2022-08-24 08:20 UTC, aminlatifi requested changes
These three github action yaml files were copied from another place by @mendesfabio, they are not designed for our use case. 
Update to develop branch must be deployed to two staging subgraphs (goerli and xdai) and updates to the main branch consequently must be deployed to two production subgraphs.

A better way is to remove these three and create a more cleaner version of this
https://github.com/Giveth/giv-token-subgraph/blob/develop/.github/workflows/graph.yml

2022-08-24 11:26 UTC, mendesfabio commented
I actually believe these actions were thought for every Subgraph deployment workflow, and Giveth doesn't have a special use case to be different. IMHO having it all in one file isn't more cleaner, but quite the opposite -- if one wants to know which actions run on push to main, for instance, has to read all the code. I would suggest to have 3 actions: 1 on every PR that runs lint and build, 1 on push to dev to deploy the staging Subgraps, 1 on push to main to deploy the prod Subgraphs.

2022-08-24 12:01 UTC, aminlatifi commented
> I actually believe these actions were thought for every Subgraph deployment workflow, and Giveth doesn't have a special use case to be different. IMHO having it all in one file isn't more cleaner, but quite the opposite -- if one wants to know which actions run on push to main, for instance, has to read all the file. I would suggest to have 3 actions: 1 on every PR that runs lint and build, 1 on push to dev that deploys the staging Subgraps, 1 on push to main that deploys the prod Subgraphs.

I agree with the idea of having three github action files with the purposes you mentioned. The issue is that the action files that have been initially pushed to this code are not doing those jobs. We have not lining check, and the two others for deploying develop and main branch updates are not configured to work. 
@mateodaza can you create or modify current github action files to address requirements?

2022-08-24 12:15 UTC, mendesfabio commented
The template I started this repository with has a script for lint and ESLint configured. You guys should be able to test if everything still works by running `yarn lint`

2022-08-24 12:51 UTC, mateodaza commented
Thanks a lot for your feedback guys! I'll get to do those changes @mendesfabio @aminlatifi

2022-08-25 12:18 UTC, aminlatifi commented on .github/workflows/graph-build.yaml
> +        run: yarn build:deployment-7:xdai
Because that's the only permanent env and others can change in the future

2022-08-25 12:30 UTC, aminlatifi commented on .github/workflows/graph.yaml
> -    branches: [master]
Good, plaese change the name of file too

2022-08-25 12:33 UTC, aminlatifi commented on src/mappings/uniswapV3/uniswapV3RewardTokenMapping.ts
> +  // Approval,
Let's remove these comments

2022-08-25 15:47 UTC, mendesfabio requested changes
@mateodaza left 2 comments. Please change the other deployment actions if you agree with the suggestions.

2022-08-25 15:47 UTC, mendesfabio commented on .github/workflows/graph-develop.yaml
> +          graph_config_file: $GRAPH_CONFIG_FILE
I don't see the reason to use env here, only `GRAPH_ACCESS_TOKEN` is secret. I suggest removing all env vars and writing the values directly here.

2022-08-25 15:48 UTC, mendesfabio commented on .github/workflows/graph-develop.yaml
> +          graph_config_file: $GRAPH_CONFIG_FILE
For reference, this is how I would like it https://github.com/balancer-labs/balancer-subgraph-v2/blob/master/.github/workflows/graph.yml#L24

2022-08-26 16:30 UTC, mateodaza commented
Thanks @mendesfabio and @mohammadranjbarz for your feedback and suggestions!

2022-08-26 22:39 UTC, mendesfabio approved these changes

2022-08-26 22:42 UTC, mendesfabio commented
I'll take this opportunity to remind you guys that Subgraph Studio has released support to Gnosis Chain. You're probably aware but Edge&Node is sunsetting Hosted Service in some months. I strongly recommend you guys start the process for migration -- if you need help, reach out to me on TG.

2022-08-27 09:49 UTC, aminlatifi commented
> Gnosis Chain

Nice to know. But they have not updated their UI! only mainnet and rinkeby are mentioned
<img width="939" alt="image" src="https://user-images.githubusercontent.com/5684607/187024904-203f492a-c5cf-4397-9d22-0daeab393790.png">

2022-08-27 11:01 UTC, mendesfabio commented
should be live very soon. anyway, you could start with Ethereum.

2022-08-29 15:00 UTC, MoeNick commented
@mateodaza @aminlatifi pls take a look again.

2022-08-31 05:40 UTC, aminlatifi requested changes
Also I unresolved https://github.com/Giveth/givpower-subgraph/pull/21#discussion_r955338337

2022-08-31 05:40 UTC, aminlatifi commented on .github/workflows/graph-develop.yaml
> +    needs: [lint, deploy-staging-goerli]
Why do we need this deployment to happen after goerli one?

2022-08-31 05:40 UTC, aminlatifi commented on .github/workflows/graph-main.yaml
> +    needs: [lint, deploy-mainnet]
The same

2022-09-01 12:39 UTC, aminlatifi requested changes

2022-09-02 04:31 UTC, aminlatifi requested changes

2022-09-02 04:31 UTC, aminlatifi commented on .github/workflows/graph-develop.yaml
> +      - name: Install
We install dependencies two times! once in lint and once in generate-manifest. We can depend generate-manifest to lint
```
    needs: [lint]
```
And for others just make generate-manifest the dependency

2022-09-04 07:14 UTC, aminlatifi requested changes

2022-09-04 07:14 UTC, aminlatifi commented on .github/workflows/graph-develop.yaml
> +      - name: Lint
This name is wrong

2022-09-04 07:14 UTC, aminlatifi commented on .github/workflows/graph-develop.yaml
> +        run: yarn --frozen-lockfile
Why do we install these dependencies again? they are already installed in dependency jobs

2022-09-04 07:14 UTC, aminlatifi commented on .github/workflows/graph-develop.yaml
> +        run: yarn --frozen-lockfile
Like above

2022-09-04 07:14 UTC, aminlatifi commented on .github/workflows/graph-main.yaml
> +      - name: Lint
This name must be changed

2022-09-04 07:14 UTC, aminlatifi commented on .github/workflows/graph-main.yaml
> +        run: yarn --frozen-lockfile
like above, we don't need to install again

2022-09-04 07:14 UTC, aminlatifi commented on .github/workflows/graph-main.yaml
> +          graph_subgraph_name: givpower-subgraph
This path is wrong

2022-09-04 07:14 UTC, aminlatifi commented on .github/workflows/graph-main.yaml
> +          graph_subgraph_name: givpower-subgraph
giveth-economy-second-mainnet

2022-09-04 07:14 UTC, aminlatifi commented on .github/workflows/graph-main.yaml
> +        run: yarn --frozen-lockfile
Like above don't need to reinstall

2022-09-04 07:14 UTC, aminlatifi commented on .github/workflows/graph-main.yaml
> +          graph_subgraph_name: giveth-economy-xdai
This name is wrong 
giveth-economy-second-xdai

2022-09-04 08:14 UTC, merged

2022-09-04 08:14 UTC, aminlatifi commented
@mateodaza I fixed myself remaining issues